### ISSUE TITLE
Simulation Strategy

### ISSUE THREAD

**Issue by alex-d13** [omnideconv/SimBu#2]
Overall strategy: sample all reads of cells from a list of cell-ids with known cell-type

- a simple database (e.g. sqlite, even a flat textfile could do it) that stores: cell-id, path to fastqs, cell-type annotation
- sample n cells from the list in the wanted cell-type composition
- simply concatenate all the fastq files
- run salmon/kallisto to obtain TPM.

How to store reads?
Suggestion by Markus: use k-mer approach (like kallisto index https://pachterlab.github.io/kallisto/manual); then use k-mers to calculate TPM values. This could increase runtime and decrease memory space.

Questions on this:

1. How much would you expect to reduce the file size with respect to the (zipped) FASTQ files? 
2. Can it slow down or complicate the downstream analysis (e.g. TPM and count quantification)?
3. Would it make sense to start with the read-based strategy and, if we have more time, convert it to a k-mer based approach?

**Comment by mlist** [comment]
Adding to the questions here, I think storing the kallisto index (generated with the pseudo command) might speed everything up as the pseudoalignment step has to be performed only once. I'd definitely give this a try. I'm not sure about space requirements but as FASTQ files have quite a bit of overhead it might be better, too. Please try it out so we know if it is a feasible approach.
