### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by grst** [omnideconv/SimBu#33]
I've seen you have something like `v0.99.x` now. Is this some bioconductor thing? 

In general, I'd recommend to go with https://semver.org versions. 

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>     MAJOR version when you make incompatible API changes,
>     MINOR version when you add functionality in a backwards compatible manner, and
>     PATCH version when you make backwards compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

**Comment by alex-d13** [comment]
Yep, thats a bioconductor thing: https://contributions.bioconductor.org/versionnum.html

Basically, you have to keep the 0.99.X until the package is accepted and then move on to 1.0.0.

**Comment by grst** [comment]
I see, thanks!
