### ISSUE TITLE
Example/tutorial operate/access output from simulate_bulk

### ISSUE THREAD

**Issue by slieped** [omnideconv/SimBu#42]
First, congratz for the excellent work and thanks for making it public!

# Enhancement
Add an example on how to access the output data from the "simulate_bulk" function

Whereas in the example tutorial its super clear that the output its a SummarizedExperiment object, for more "noobie" users it might be good to show how to access to simulated pseudobulk from the output (i.e that the return is a list and should be accessed via outsimulation["bulk"])

Close and ignore this if you think its not needed at all.
Again, thanks!

V

**Comment by alex-d13** [comment]
Hi,

Thanks for the nice feedback. 
So you are talking about extending this section here: http://omnideconv.org/SimBu/articles/simulator_input_output.html#output, right?

Best,
Alex
