### ISSUE TITLE
Bug in defining cell_id_col and cell_type_col in dataset_seurat function

### ISSUE THREAD

**Issue by orange-whale** [omnideconv/SimBu#43]
Hi 

Thank you very much for this great tool!

I've experienced a bug in the dataset_seurat function for converting a seurat object to a SummarizedExperiment object. From the manual https://bioconductor.org/packages/devel/bioc/manuals/SimBu/man/SimBu.pdf it appears that you should be able to use the original column name for the ID and cell-type columns in the seurat metadata slot, but when i tried that the function did not work. When I instead changed the name of those to columns to ID and cell_type the function worked again. 

Best regards

**Comment by alex-d13** [comment]
Hi,

Thanks for using Simbu :)
Sorry, I might have missed your issue previously. Should be fixed in the next bioconductor update.

Best,
Alex
