### ISSUE TITLE
samples vs simulations

### ISSUE THREAD

**Issue by mea2712** [omnideconv/SimBu#53]
Hey there
What would be the difference between running 1 simulation with 1000 samples, and running 10 simulations with 100 samples each (all 10 simulations with the same ncells, and scenario)?
Thanks!

**Comment by alex-d13** [comment]
Hi,

Good question! In fact, it would not make a difference. For example the random scenario will lead to the same result with both approaches, though you can use a different seed for each of the 10 simulations if you wish.

**Comment by mea2712** [comment]
I see. Good point the random feeds. Thanks for your answer!
